### ISSUE TITLE
Roomba e5 support

### ISSUE THREAD

**Issue by kgerlich** [Zefau/ioBroker.roomba#1]
Hi,

first let me say thanks for your effort,I was just about to do the iobroker adapter with dorita980 myself but you fortunately beat me to it. Very appreciated.

Now, I have an e5 and I've seen dorita980 works with it and also tried it myself. 

However, with the iobroker adapter I only get to 

2018-12-14 14:18:51.252 - debug: roomba.0 Roomba Connection established.

The roomba.o object has state but there's only _connected = true in there.

So, I wonder what I can help to get this to work.

Many thanks again,
Klaus

**Comment by kgerlich** [comment]
I debugged quickly,

remove the 'pose' preference and it'll work or e5. I haven't checked what your code needs this for but at least states and commands and such show up and triggering a clean run works also.

    getPreferences: (decode) => waitPreferences(decode, ['cleanMissionStatus', 'cleanSchedule', 'name', 'vacHigh', 'signal'], false),

I had noticed in my testing that some of the preferences weren't returning at all. Also some of the other robot functions don't seem to return results.

Klaus

**Comment by Zefau** [comment]
Can you provide the software version of your Roomba e5?
Out of all channels / states (see https://github.com/Zefau/ioBroker.roomba#channels--states), which ones stay empty with your Roomba?

**Comment by Zefau** [comment]
@kgerlich Can you provide the software version of your Roomba e5? Thanks in advanced.

**Comment by gik007** [comment]
Hi @Zefau I also have a Roomba e5. The software version of my device is 3.4.42. 

@kgerlich, how did you manage to get the password out of your Roomba e5? I haven't been able so far. When I try (using bin/getpassword.js), I get an error message "Error getting password. Follow the instructions and try again." 

Thanks in advance for your help!

**Comment by kgerlich** [comment]
Worked for me but I wrote myself a quick iobroker adapter that is more simple and works for me based on dorita980 as well.

Have followed instructions on dorita980? Press home in dock until melody and the run getpassword.js?

Klaus

Von meinem iPad gesendet

**Comment by Zefau** [comment]
Support for e5 / 600 series added in [dorita980@3.1.0](https://github.com/koalazak/dorita980/issues/71#issuecomment-452308957). Added in ioBroker.roomba@0.4.0.
