### ISSUE TITLE
State of the current status is changing with a big delay

### ISSUE THREAD

**Issue by linchen4000** [Zefau/ioBroker.roomba#10]
* Roomba Model: 980
* Roomba Software Version: 0.4.4

In the past with previous versions I used the state of the current status of the robot for some scripts. Now they are not working anymore, because the state is changing / updating the current status like "run", "charge", ... with a big delay, if at all.

Now, for example the robot is cleaning almost 30 min and the state is still set to an old value "stop" instest of "run" probably.

Other states like the rawData is updated very often. So no general problem with updates from the robot.

**Comment by linchen4000** [comment]
The value has changed to "run" 34 min after starting the robot.

**Comment by linchen4000** [comment]
And now, 11-12 hrs since the cleaning process is done and the robot is docked, the status is still on "run".

**Comment by Zefau** [comment]
I will have a look at this in the next days. Thanks for reporting.

**Comment by Zefau** [comment]
For some reason, it is working perfectly fine for me. 
Though, I have refactored some parts and added a debug option (to be activated in the settings).
Please install the current v0.4.5, activate the option and change the adapter log to "debug".

After that, please trigger to start a Roomba mission and provide the log (only the first minutes are relevant).

**Comment by linchen4000** [comment]
Okay thanks, now it's working again. 

With 0.4.4 the state "_connected" changed to false when I triggerd a start, and was true again, when the roomba docked.

Now with 0.4.5 it's the normal delay of 30-60 sec. for updating the status state again.
I think it is not necessary to provide the log anymore.

Thank you for your work!
