### ISSUE TITLE
Adapter works with 895 

### ISSUE THREAD

**Issue by holger05** [Zefau/ioBroker.roomba#11]
* Roomba Model: 895
* Roomba Software Version: 3.2.40+69

Controll works fine
Limited states because of roomba typ

**Comment by Zefau** [comment]
Thanks for the information! Limited in what regard? Are you having a map of the clean area within the official Roomba App? Is this working in the adapter as well? What objects / states (see https://github.com/Zefau/ioBroker.roomba#channels--states) are created within ioBroker?

**Comment by holger05** [comment]
The feature map in the app is not available with the 895.

Any of this status are available in the object list:
states | - | _connected | Connection state
-- | -- | -- | --
states | - | battery | Battery level of the robot
states | - | binFull | State whether bin status is full
states | - | binInserted | State whether bin is inserted
states | - | docked | State whether robot is docked
states | - | signal | Signal strength
states | - | status | Current status of the robot

![image_2019_03_22T10_07_42_223Z](https://user-images.githubusercontent.com/33962350/54815657-c70d8900-4c92-11e9-8fe7-3f79eee4abf0.png)

**Comment by Zefau** [comment]
Great, thanks! Just read your post (https://forum.iobroker.net/post/245274) in the forum as well.
I will updated the docs.
