### ISSUE TITLE
Map displayed upside down

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.roomba#12]
Map is mirrored and upside down, see https://forum.iobroker.net/post/240589

**Comment by senger1985** [comment]
will you try to fix it in the next time

**Comment by Zefau** [comment]
I have a look at this tomorrow.

**Comment by senger1985** [comment]
Thx

**Comment by Zefau** [comment]
mirrored map by https://github.com/Zefau/ioBroker.roomba/commit/fdbd480d9926547fb933308d15267c307122a7c4
