### ISSUE TITLE
Roomba 895 support (firmware v3 support)

### ISSUE THREAD

**Issue by Leseratte10** [Zefau/ioBroker.roomba#2]
The readme states that roomba 895 is not yet supported, is that in progress somehow or is there anything we can do to help with that?

Grabbing IP, username and password works, then, when connecting to the robot, this error is in the log file: 

```

host.server | 2018-12-20 17:44:04.719 | error | instance system.adapter.roomba.0 terminated with code 1 ()
-- | -- | -- | --
host.server | 2018-12-20 17:44:04.719 | error | Caught by controller[0]:     at TLSWrap.onread (net.js:607:20)
host.server | 2018-12-20 17:44:04.719 | error | Caught by controller[0]:     at TLSSocket.Readable.push (_stream_readable.js:208:10)
host.server | 2018-12-20 17:44:04.719 | error | Caught by controller[0]:     at readableAddChunk (_stream_readable.js:250:11)
host.server | 2018-12-20 17:44:04.719 | error | Caught by controller[0]:     at addChunk (_stream_readable.js:263:12)
host.server | 2018-12-20 17:44:04.719 | error | Caught by controller[0]:     at TLSSocket.emit (events.js:211:7)
host.server | 2018-12-20 17:44:04.719 | error | Caught by controller[0]:     at emitOne (events.js:116:13)
host.server | 2018-12-20 17:44:04.719 | error | Caught by controller[0]:     at TLSSocket.ondata (_stream_readable.js:639:20)
host.server | 2018-12-20 17:44:04.719 | error | Caught  by controller[0]:     at Writable.write  (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
host.server | 2018-12-20 17:44:04.719 | error | Caught  by controller[0]:     at writeOrBuffer  (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
host.server | 2018-12-20 17:44:04.719 | error | Caught  by controller[0]:     at doWrite  (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
host.server | 2018-12-20 17:44:04.719 | error | Caught  by controller[0]:     at Writable.writable._write  (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/node_modules/mqtt/lib/client.js:302:5)
host.server | 2018-12-20 17:44:04.718 | error | Caught  by controller[0]:     at work  (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/node_modules/mqtt/lib/client.js:292:12)
host.server | 2018-12-20 17:44:04.718 | error | Caught  by controller[0]:     at MqttClient._handlePacket  (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/node_modules/mqtt/lib/client.js:350:12)
host.server | 2018-12-20 17:44:04.718 | error | Caught  by controller[0]:     at MqttClient._handleConnack  (/opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/node_modules/mqtt/lib/client.js:920:15)
host.server | 2018-12-20 17:44:04.718 | error | Caught by controller[0]: Error: Connection refused: Not authorized
host.server | 2018-12-20 17:44:04.717 | error | Caught by controller[0]:     ^
host.server | 2018-12-20 17:44:04.717 | error | Caught by controller[0]:     throw e;
host.server | 2018-12-20 17:44:04.717 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.roomba/node_modules/dorita980/lib/v2/local.js:30
```

**Comment by Zefau** [comment]
Thanks for your message. I don't own a Roomba 895 myself, so it is difficult to add support.
Your error message states that the obtained credentials are wrong (`Error: Connection refused: Not authorized`).
Which software version is your Roomba running on?

**Comment by GuardianAngel-78** [comment]
how to install the **admin panel of ioBroker.roomba**
thanks for help

**Comment by Zefau** [comment]
Roomba 895 - Firmware 3.2.10
https://forum.iobroker.net/viewtopic.php?f=20&t=8092&start=40#p199225
https://forum.iobroker.net/viewtopic.php?f=20&t=8092&start=60#p199261
https://forum.iobroker.net/viewtopic.php?f=20&t=8092&start=60#p199367

**Comment by Zefau** [comment]
@Leseratte10 Der Roomba 895 (Firmware v3) versucht über eine gesicherte MQTT Verbindung zu connecten. Hast du Erfahrung mit Programmierung? Dann können wir gemeinsam versuchen die Verbindung zu knacken und v3 in den Adapter integrieren.

**Comment by Zefau** [comment]
https://forum.iobroker.net/viewtopic.php?f=20&t=8092&p=210129#p210129

**Comment by Zefau** [comment]
See also issue https://github.com/koalazak/dorita980/issues/71

**Comment by Zefau** [comment]
@Leseratte10 Please install (by running `iobroker install https://github.com/Zefau/ioBroker.roomba` following by `iobroker upload roomba`) and check out support for Roomba e5 and 600 series, which could work on 800 series as well.

**Comment by Zefau** [comment]
@Leseratte10 Can you confirm that the current version is running with Roomba 895?

**Comment by GuardianAngel-78** [comment]
Wich Language is your mother Language. My one is German...
I got a 980..I will try it an give you reguest. 
In further versions I lost connection to the roomba...
With best regards Stefan 


Gesendet von Yahoo Mail für iPhone


Am Montag, Februar 11, 2019, 5:36 PM schrieb Zefau <notifications@github.com>:


@Leseratte10 Can you confirm that the current version is running with Roomba 895?
