### ISSUE TITLE
Charging station isn't on the right position on minimap

### ISSUE THREAD

**Issue by senger1985** [Zefau/ioBroker.roomba#23]
* Roomba Model: 966
* Roomba Software Version: v2.4.6-3

If my Roomba is on the charging station, it shows not the right position, on the minimap.(yellow house image)

I'ven't changed the position on any time

**Comment by Zefau** [comment]
Thanks for the reporting the issue. Apparently, the house indicates the starting position of the Roomba, not exactly the charging station. 

I will have a look at this, if I can put both on the map.

**Comment by Zefau** [comment]
I have reworked placing home icon with v1.0.2. Could you please test and verify if it was successful?

**Comment by senger1985** [comment]
I'll test it tomorrow and will tell you the result

**Comment by senger1985** [comment]
I don't know, could be, that my Roomba lost for a moment the conection, to the station.
But I've seen, that the Robot-Icon hasn't move on the map and as the robot finished the current job the Icon stay anywhere on the map.
The Station-Icon is on the right possison.

**Comment by Zefau** [comment]
ah ok, I probably got you wrong then. The home icon (yellow house) is placed correctly, but the Roomba icon is not updated at the end of the mission (when it is moving to the yellow house)?

**Comment by senger1985** [comment]
Exactly.

**Comment by Zefau** [comment]
I updated the repository to address this bug. It is absolutely untested, but I will do so this week. If you'd like you can try and install the current Github version and join testing.

**Comment by senger1985** [comment]
At this time I only get the version 1.0.3 via github (octocat-icon)
This version is from 2019-23-07

**Comment by Zefau** [comment]
That's correct, I haven't changed the version number yet. The change is included though.

**Comment by senger1985** [comment]
Okay, than I'll test it tomorrow and I'll report

**Comment by senger1985** [comment]
I don't know what the problem is, but the map is now rotated 180 degrees and the robot is in another place.

But now the home icon (yellow house) is in the right place.

I have no problem with that anymore.
Main thing he shows me where he is driving long.

if you want, you can close the case.

**Comment by Zefau** [comment]
How many times have you run the Roomba that the map was rotated?
I have the same issue every now and then and I suspect the data transmitted by the Roomba is differently for some reason.

Please observe this issue with the rotated map and I would appreciate if you report back here in a week or so.

Thank you very much for your support!

**Comment by senger1985** [comment]
I'll do some test runs in the next few days

**Comment by senger1985** [comment]
I have find out that I have connection problems.
My Robby always stays in the same position on the map and the icon does not move.
I have to send it in anyway because I have problems with charging.
I'll give an update if I can continue testing the adapter

**Comment by Zefau** [comment]
Connection problems are also reported in the forum https://forum.iobroker.net/topic/7657/irobot-roomba-adapter/225.

**Comment by Zefau** [comment]
I publish a version v1.0.4. Please test this one. It updates the dependencies to the latest version, which might fix the problem.

**Comment by Zefau** [comment]
Connection issue has been fixed in v1.0.5. Please install and try again.
If the error persists, please open a dedicated issue for that problem.
