### ISSUE TITLE
Map is not drawn

### ISSUE THREAD

**Issue by senger1985** [Zefau/ioBroker.roomba#31]
* Roomba Model: 966
* Roomba Software Version: v2.4.6-3

I have installed as it is written in the description:
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
sudo npm install canvas --unsafe-perm=true

But still get the message:
(14287) Canvas not installed! Thus, no map drawings are possible.

If you need the debug log, let me know

**Comment by Zefau** [comment]
I have to rework the description, it's not precise enough.

Please run `sudo npm install canvas --unsafe-perm=true` directly in the ioBroker.roomba folder (`/opt/iobroker/node_modules/iobroker.roomba`).

**Comment by senger1985** [comment]
Thank you for your prompt reply.
I will test it later and then close the issue if it works.

**Comment by senger1985** [comment]
Great it works again
