### ISSUE TITLE
S9+ support acknowledged!

### ISSUE THREAD

**Issue by Killi138** [Zefau/ioBroker.roomba#34]
Hi,

I just want to inform you that my S9+ is also supported. It is missing in the table of supported models.
Robot Data:
`{ ver: '3',
  hostname: 'iRobot-B4176B245DF2486691E867153BC0xxxx',
  robotname: 'Jürgen',
  robotid: 'B4176B245DF2486691E867153BC0xxxx',
  ip: '192.168.xx.xx',
  mac: 'xx:14:xx:16:64:xx',
  sw: 'soho+3.2.4+soho-release-rt419+7',
  sku: 's955840',
  nc: 0,
  proto: 'mqtt',
  cap:
   { carpetBoost: 1,
     binFullDetect: 1,
     dockComm: 1,
     maps: 3,
     edge: 0,
     pmaps: 2,
     tLine: 2,
     area: 1,
     eco: 1,
     multiPass: 2,
     pose: 1,
     team: 1,
     pp: 0,
     '5ghz': 1,
     prov: 3,
     sched: 1,
     svcConf: 1,
     ota: 2,
     log: 2 },
  blid: 'xxxxxxxxx' }`

In the Home App the firmware is:
3.2.4

It is working including the image.

**Comment by Zefau** [comment]
Very much appreciated! I will update the documentation.
